### ISSUE TITLE
Maybe an improvement, a suggestion.

### ISSUE THREAD

**Issue by VagantemNumen** [IMcPwn/Reminder#6]
You currently call 

``` go
prefix, err := s.User("@me")
```

at least three times in your code.
You may want to make it a single call and store it in a global variable to minimize the calls made to the API.

Just a suggestion.

**Comment by IMcPwn** [comment]
Actually I do this to make sure I'm still logged into the API and there wasn't some network failure.

You could be right though, other API calls might catch that and storing that variable might be a better idea.

Or maybe I could make a function checkLoggedIn to reduce code duplication if not.

**Comment by IMcPwn** [comment]
I think making that call less is better. It will return the same thing each time if successful so if there's a network failure, sending the message will catch that. 

I'll work on improving that. Thanks for the suggestion!

**Comment by IMcPwn** [comment]
Commit bbd5e565721111b28690d881e7cf926e563bbc06 reduces this problem. 

If you have any other suggestions feel free to reopen.

**Comment by IMcPwn** [comment]
Reducing the problem even more: commit 1d092132bd35a8f0b9a75d5cc9e84971eb109071

**Comment by VagantemNumen** [comment]
You could use,

``` go
defer SafeDB.mux.Unlock()
```

once and avoid repeating it so many times.
And for case insensitive commands you can maybe uppercase the m.Content when doing the compare.
Also you may want to fail some of those silently since that is going to clutter the chat or optionally delete the error message in the 10s window, where you do not get rate limited, from the time of sending.

I hope you do not mind these suggestions.

**Comment by IMcPwn** [comment]
I'm always open to suggestions. Thank you, I'll work on these.

**Comment by VagantemNumen** [comment]
Well that is nice since apparently I am in a mood where I do not want to do any work of my own and am just reading other projects code.

**Comment by IMcPwn** [comment]
If you want to actually work on my code you can fork + create pull requests. I'd really appreciate it.

**Comment by VagantemNumen** [comment]
I am not really that good at Go unfortunately. I have only started with Go about 20 days or so ago. But if I do find something that requires more than few lines of code I shall try do so.

**Comment by IMcPwn** [comment]
I started Go around 25 days ago as well, most of these tricks I still haven't learned yet.

Thanks!

**Comment by VagantemNumen** [comment]
So I forked this and ran on my PC, and apparently however you are storing the time is messing up with the way reminders are working. When I set a reminder for 5mins I got notified in just few seconds.
After that I have not look into it much to identify the issue due to some reallife problems.

**Comment by IMcPwn** [comment]
If you have any other information (e.g., reminder.log, and reminder.db) I'd be glad to take a look.

**Comment by VagantemNumen** [comment]
I will look into it and report back to you when I have time. Also,

``` go
// TODO: Improve method of string concatenation
    var message string
    for i := 3; i < len(content); i++ {
        message = message + " " + content[i]
}
```

Can be writen as,

``` go
message := content[(len(content[0])+len(content[1])+len(content[2])+2):]
```

You may need to edit it a bit. It is just a rough estimate of how it would look like.
